Add missing Lib to target_link_libraries
########################
Linking C executable mmal_buffer_demo
Error :
undefined reference to symbol 'clock_gettime@@GLIBC_2.4'

Add Lib rt
########################

Linking C executable mmal_opencv_demo
Error : 
undefined reference to symbol 'sem_post@@GLIBC_2.4'
undefined reference to symbol 'clock_gettime@@GLIBC_2.4'
undefined reference to symbol 'lrint@@GLIBC_2.4'
undefined reference to symbol 'FT_New_Face'

Add Lib pthread rt m freetype

########################
Linking C executable mmal_video_record
Error :
undefined reference to symbol 'clock_gettime@@GLIBC_2.4'

Add Lib rt
########################